#!/usr/bin/zsh
python mottracker_app.py \
    --sequence_dir=/Users/mark/MOT/MOT16/test/MOT16-06 \
    --detection_mat=/Users/mark/MOT/resources/detections/MOT16_POI_test/MOT16-06.npy \
    --output=../ds-output/MOT16-06.txt \
    --min_confidence=0.3 \
    --max_cosine_distance=0.2 \
    --nn_budget=100 \
    --budget_association_threshold=1.0 \
    --budget_detection_threshold=0.3 \
    --matching_time_depth=30
