#!/usr/bin/zsh
python mottracker_app.py \
    --sequence_dir=/home/mark/MOT/MOT16/train/MOT16-10 \
    --detection_mat=/home/mark/MOT/resources/detections/MOT16_POI_train/MOT16-10.npy \
    --output=../ds-output/MOT16-10.txt \
    --min_confidence=0.3 \
    --max_cosine_distance=0.2 \
    --nn_budget=100 \
    --budget_association_threshold=1.0 \
    --budget_detection_threshold=0.3 \
    --matching_time_depth=30
